
services:
  worker:
    build:
      context: .
    image: vostok33/orderflow
    container_name: bbws_worker
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redis
    container_name: rMaster
    env_file: .env
    environment:
      - REDIS_PASS=${REDIS_PASS}
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASS}"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data




